# Generated by Django 5.0.2 on 2025-03-22 18:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/df6ndrlj2/image/upload/v1739969127/default_sklyca.png', max_length=255, verbose_name='profile'),
        ),
    ]
